FROM node:alpine
ENV   https_proxy=http://10.101.65.50:8080/
ENV   http_proxy=http://10.101.65.50:8080/

RUN mkdir -p '/app'
WORKDIR '/app'

COPY package.json /app/
RUN npm install

COPY . .

CMD ["npm", "run", "start"]
